id: P009535
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ34105
  title: གསུང་འབུམ། བློ་གྲོས་གྲགས་པ།
  author: ''
  volumes:
    8710ec9c256447868d415ba92e3b8bae:
      image_group_id: I1KG16815
      title: ''
      volume_number: 1
      total_pages: 447
    aa45d8cfc585446b8b8d4896ffa34aae:
      image_group_id: I1KG16816
      title: ''
      volume_number: 2
      total_pages: 505
    9032b028329a42f887594eb1f3ae0113:
      image_group_id: I1KG16817
      title: ''
      volume_number: 3
      total_pages: 495
    9e3ab975cacc477099e5255e5d7d738e:
      image_group_id: I1KG16818
      title: ''
      volume_number: 4
      total_pages: 549
    b86a49825d504ee5b8832f74de253f1a:
      image_group_id: I1KG16819
      title: ''
      volume_number: 5
      total_pages: 521
    4645e6fb1b0b41db9eeb6d066c4cc471:
      image_group_id: I1KG16820
      title: ''
      volume_number: 6
      total_pages: 511
    86da9ca492ea4f5492db60a4e46f3f24:
      image_group_id: I1KG16821
      title: ''
      volume_number: 7
      total_pages: 395
    350ad3ad115143bb9566862966fb8cb7:
      image_group_id: I1KG16822
      title: ''
      volume_number: 8
      total_pages: 447
    244b97836532417ea84269c9b7c3c2d7:
      image_group_id: I1KG16823
      title: ''
      volume_number: 9
      total_pages: 591
    ea5ae69bd4524a01801b8ebd1b55c9e5:
      image_group_id: I1KG16824
      title: ''
      volume_number: 10
      total_pages: 487
