id: I71177739
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:10:02+00:00'
last_modified: '2022-06-08T11:43:12.901567+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ34105
  title: གསུང་འབུམ། བློ་གྲོས་གྲགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    46E4:
      image_group_id: I1KG16815
      title: ''
      total_pages: 447
      order: 1
      base_file: 46E4.txt
    C9C6:
      image_group_id: I1KG16816
      title: ''
      total_pages: 505
      order: 2
      base_file: C9C6.txt
    '7776':
      image_group_id: I1KG16817
      title: ''
      total_pages: 495
      order: 3
      base_file: 7776.txt
    1B99:
      image_group_id: I1KG16818
      title: ''
      total_pages: 549
      order: 4
      base_file: 1B99.txt
    E999:
      image_group_id: I1KG16819
      title: ''
      total_pages: 521
      order: 5
      base_file: E999.txt
    4D68:
      image_group_id: I1KG16820
      title: ''
      total_pages: 511
      order: 6
      base_file: 4D68.txt
    55BB:
      image_group_id: I1KG16821
      title: ''
      total_pages: 395
      order: 7
      base_file: 55BB.txt
    464A:
      image_group_id: I1KG16822
      title: ''
      total_pages: 447
      order: 8
      base_file: 464A.txt
    361F:
      image_group_id: I1KG16823
      title: ''
      total_pages: 591
      order: 9
      base_file: 361F.txt
    5FF7:
      image_group_id: I1KG16824
      title: ''
      total_pages: 487
      order: 10
      base_file: 5FF7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
